export {
  CANVAS_BACKGROUNDS_BY_THEME,
  COLOR_PALETTES,
  DARK_THEME_BACKGROUND_COLORS,
  DARK_THEME_STROKE_COLORS,
  DEFAULT_CANVAS_BACKGROUND,
  DEFAULT_ELEMENT_STYLE,
  DEFAULT_ELEMENT_STYLE_BY_THEME,
  DEFAULT_GRID_COLOR,
  DEFAULT_FILL_STYLE,
  DEFAULT_FILL_WEIGHT,
  DEFAULT_OPACITY,
  DEFAULT_SELECT_TOOL,
  DEFAULT_SELECTED_SLOPPINESS,
  DEFAULT_SLOPPINESS_GAP,
  DEFAULT_STROKE_WIDTH,
  DEFAULT_STROKE_STYLE,
  DEFAULT_UI_SCALE,
  EMPTY_COLLECTION_LENGTH,
  FIRST_ARRAY_INDEX,
  GRID_CELL_SIZE,
  GRID_COLORS_BY_THEME,
  HISTORY_LIMIT,
  LIGHT_THEME_BACKGROUND_COLORS,
  LIGHT_THEME_STROKE_COLORS,
  MAX_UI_SCALE,
  MIN_CREATE_DRAG_DISTANCE,
  MIN_ELEMENT_SIZE,
  MIN_SELECT_DRAG_DISTANCE,
  MIN_UI_SCALE,
  PERCENT_MAX_VALUE,
  UI_SCALE_STEP,
  TEXT_ELEMENT_DEFAULT_HEIGHT,
  TEXT_ELEMENT_DEFAULT_WIDTH,
  TRANSPARENT_COLOR,
  RESIZE_HANDLES,
  SINGLE_SELECTION_COUNT
} from "kizkatt-graphic-engine";

export const COLOR_PANEL_COLUMN_COUNT = 5;
export const GRID_MAJOR_CELLS = 5;
export const GRID_FIRST_MINOR_INDEX = 1;
export const GRID_CROSS_MIN_SIZE = 1.25;
export const GRID_CROSS_MAX_SIZE = 3;
export const GRID_CROSS_CELL_RATIO = 0.11;
export const SVG_FULL_SIZE = "100%";
export const ZOOM_OUT_SYMBOL = "−";
export const ZOOM_IN_SYMBOL = "+";
